language: node_js
sudo: required
cache:
  yarn: true
script:
  - yarn install
  - cd packages/mobx-state-tree && yarn install && yarn build && yarn test && yarn run-coverage && yarn link
  - cd packages/mst-middlewares && yarn install && yarn link mobx-state-tree && yarn build && yarn test
after_success:
  - cat ./packages/mobx-state-tree/coverage/lcov.info|./packages/mobx-state-tree/node_modules/coveralls/bin/coveralls.js
node_js:
  - 9.3.0
